#!/bin/bash

printf "\r  [ \033[0;33m?\033[0m ] Clone dotfiles from github user: "
read -e git_username

mkdir -p ~/.ssh/keys
echo -e "Host github.com\n\tHostName github.com\n\tUser $git_username\n\tIdentityFile ~/.ssh/keys/${git_username}.github.ossh" >> ~/.ssh/config
wget https://www.dropbox.com/s/coq673flwncku93/github-road.ossh?dl=0 -O ~/.ssh/keys/${git_username}.github.ossh -q
chmod 600 ~/.ssh/keys/${git_username}.github.ossh
git clone git@github.com:${git_username}/dotfiles.git ~/.dotfiles
